export const lesEvaluation = [{
    id: 1,
    nomEleve: "John Doe",
    programmeEtude: "Informatique",
    nomEntreprise: "Dev Inc",
    nomSuperviseur: "Jane Doe",
    fonctionSuperviseur: "Dev",
    numeroTelephone: "514-123-4567",
    dateDebut: "2021-10-22",
    dateFin: "2021-10-27",
    planifierOrganiser: "Totalement en accord",
    respecterEngagement: "Totalement en accord",
    autonomieInitiative: "Totalement en accord",
    efficaciteEfficience: "Totalement en accord",
    capaciteApprentissage: "Totalement en accord",
    qualiteTravail: "Totalement en accord",
    espritEquipe: "Totalement en accord",
    respectRegles: "Totalement en accord",
    assiduitePonctualite: "Totalement en accord",
    gestionTache: "Totalement en accord",
    respectHierarchie: "Totalement en accord",
    respectNormes: "Totalement en accord",
    respectConfidentialite: "Totalement en accord",
    respectProcedures: "Totalement en accord",
    respectCollaborateurs: "Totalement en accord",
    respectClientPartenaire: "Totalement en accord",
    respectMateriel: "Totalement en accord",
    respectEcheancier: "Totalement en accord",
    respectBudget: "Totalement en accord",
    respectRythmeTravail: "Totalement en accord",
    respectPolitiqueEntreprise: "Totalement en accord",
    respectCodeDeontologie: "Totalement en accord",
    respectLieuDeTravail: "Totalement en accord",
    respectDroitsHumains: "Totalement en accord",
    respectLois: "Totalement en accord",
    respectReglements: "Totalement en accord",
    respectNormesSanteSecurite: "Totalement en accord",
    respectNormesQualite: "Totalement en accord",
    respectNormesEnvironnement: "Totalement en accord",
    respectNormesEthiques: "Totalement en accord",
    respectNormesSecurite: "Totalement en accord",
    respectNormesInformation: "Totalement en accord"
}]
